<?php
function comment($n){
  if($n>30 || $n< -20) echo "しつこいな、もう何も出さないから勝手にやってな";
 switch(n){
  case 7: echo "7限????";
  break;
  case 8: echo "教室しまりますよね？";
  break;
  case 9: echo "いつまで大学入るんすか？";
  break;
  case 10: echo "課題ですかですよね";
  break;
  case 11: echo "徹夜ですかですよねー(・ε・)";
  break;
  case 12: echo "もういいでしょ";
  break;
  case 13: echo "(。-ω-)zzz. . . (。ﾟωﾟ) ﾊｯ!";
  break;
  case 14: echo "ｳﾜｧｧｧｧｧｧヽ(`Д´)ﾉｧｧｧｧｧｧﾝ!";
  break;
  case 15: echo "もういいでしょ";
  break;
  case 16: echo "ﾜｰｲヽ(ﾟ∀ﾟ)ﾒ(ﾟ∀ﾟ)ﾒ(ﾟ∀ﾟ)ﾉﾜｰｲ";
  break;
  case 17: echo "疲れた？";
  break;
  case 18: echo "いつまでやるつもり";
  break;
  case 19: echo "景品とかないよ";
  break;
  case 20: echo "20おめでとう☆-(ノﾟДﾟ)八(ﾟДﾟ )ノｲｴｰｲ";
  break;
  case 21: echo "暇なんだね";
  break;
  case 22: echo "暇なんだね";
  break;
  case 23: echo "暇なんだね";
  break;
  case 25: echo "暇なんだね";
  break;
  case 26: echo "暇なんだね";
  break;
  case 27: echo "暇なんだね";
  break;
  case 28: echo "あれ？まだいたの？";
  break;
  case 29: echo "どんだけ〜( ´Д`)σ)Д`)";
  break;
  case 30: echo "お疲れ様でした。さようなら";
  break;
  case 0: echo "ZERO限目！！";
  break;
  case -1: echo "？？？？";
  break;
  case -2: echo "じ、時間が。。。";
  break;
  case -3: echo "戻れない";
  break;
  case -4: echo "はっはっは";
  break;
  case -5: echo "よくぞここまでやってた|///|ヽ(ﾟДﾟ )ﾉ|///|";
  break;
  case -6: echo "君には単位を！";
  break;
  case -7: echo "君にはA+を！！";
  break;
  case -8: echo "君には賞金を！！";
  break;
  case -9: echo "やるか（笑）";
  break;
  case -10: echo "ひ〜ま〜じ〜ん";
  break;
  case -11: echo "ひ〜ま〜じ〜ん２";
  break;
  case -12: echo "ネタ切れーーー";
  break;
  case -13: echo "hahaha";
  break;
  case -14: echo "おおお！？";
  break;
  case -15: echo "おおお！？";
  break;
  case -16: echo "おおお！？";
  break;
  case -17: echo "おおお！？";
  break;
  case -18: echo "おおお！？";
  break;
  case -19: echo "おおふ(・ε・)";
  break;
  case -20: echo "Good bye!!ヽ(ﾟдﾟ)ノ";
  break;
 } 
}

?>